### ISSUE TITLE
python/nxt_slam.py refers to "import robot", where is that code?

### ISSUE THREAD

**Issue by bentito** [jerkern/nxt_slam#1]
Nothing in the clone of the project seems to contain these methods used in nxt_slam.py:

DifferentialRobot(...) and ExactDifferentialRobot(...)

**Comment by jerkern** [comment]
Is the pyParticleEst project in your python path?
( https://github.com/jerkern/pyParticleEst ,
  http://www.control.lth.se/Staff/JerkerNordh/pyparticleest.html )

**Comment by bentito** [comment]
Yes, but it looks like robot.py, as well as PF and PS are now in subdirectories, 'models' and 'test' respectively. I think that means you need to either make them true modules and add an **init**.py to the suddirs and refer them as import models.robot, etc.  Or, add the subdirs to the path. I added the subdirs to the path and it seems to run now. Thanks!
